FROM php:8.1-cli-alpine3.15

WORKDIR /tmp/

# 1. Install build dependencies and ODBC dependencies
RUN apk update && apk add --no-cache \
    curl \
    gnupg \
    unixodbc \
    unixodbc-dev \
    linux-headers \
    autoconf \
    make \
    g++ \
    gcc \
    libc-dev \
    pkgconf

# 2. Install SQL Server ODBC drivers and tools
# Based on Microsoft's Alpine SQL Server driver packages

RUN curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/msodbcsql18_18.0.1.1-1_amd64.apk \
    && curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/mssql-tools18_18.0.1.1-1_amd64.apk \
    && curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/msodbcsql18_18.0.1.1-1_amd64.sig \
    && curl -O https://download.microsoft.com/download/b/9/f/b9f3cce4-3925-46d4-9f46-da08869c6486/mssql-tools18_18.0.1.1-1_amd64.sig

RUN curl https://packages.microsoft.com/keys/microsoft.asc | gpg --import - \
    && gpg --verify msodbcsql18_18.0.1.1-1_amd64.sig msodbcsql18_18.0.1.1-1_amd64.apk \
    && gpg --verify mssql-tools18_18.0.1.1-1_amd64.sig mssql-tools18_18.0.1.1-1_amd64.apk

RUN yes | apk add --allow-untrusted msodbcsql18_18.0.1.1-1_amd64.apk \
    && yes | apk add --allow-untrusted mssql-tools18_18.0.1.1-1_amd64.apk

# 3. Set php.ini
RUN cp /usr/local/etc/php/php.ini-development /usr/local/etc/php/php.ini \
    && pecl config-set php_ini /usr/local/etc/php/php.ini

# 4. install php drivers for sqlsrv / pdo_sqlsrv
# Latest pdo_sqlsrv requires PHP 8.3+, but this image uses PHP 8.1.
# Version 5.11.1 supports PHP 8.1.
RUN pecl channel-update pecl.php.net \
    && pecl install sqlsrv-5.11.1 pdo_sqlsrv-5.11.1 \
    && docker-php-ext-enable sqlsrv pdo_sqlsrv

# 5. Install PHP debugger
RUN pecl install xdebug \
    && docker-php-ext-enable xdebug

COPY "./webserver-setup/docker-php-ext-xdebug.ini" "/usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini"